- hosts: jumpbox 
  become: true
  gather_facts: false
  tasks:
    - name: create bin directory
      file:
        path: /root/bin
        state: directory
    - name: get script common.sh
      get_url:
        url: http://www.opentlc.com/download/ansible_bootcamp/scripts/common.sh
        dest: /root/common.sh
        mode: 0755
    - name: get script order_svc.sh
      get_url:
        url: http://www.opentlc.com/download/ansible_bootcamp/scripts/order_svc.sh
        dest: /root/order_svc.sh
        mode: 0755
    - name: install jq
      yum:
        name: jq
        state: present
    - name: Create credentials file
      copy:
        content: |
          export username={{ username }}
          export password={{ password }}
          export uri=https://labs.opentlc.com
        dest: /root/credential.rc
        mode: 0755
    - name: Run script that orders service on opentlc
      shell: source /root/credential.rc; /root/order_svc.sh -y -c 'OPENTLC Automation' -i 'Ansible Advanced' -t 1 > output.txt
      args:
        chdir: /root
    - name: Wait for environment to spin up
      pause:
        minutes: 15
     
