---
  - name: Install epel rpm from remote repo
    yum:
     name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
     state: present     
  - name: Install python ansible python dependencies
    yum:
     name: "{{ item }}"
     state: latest
    with_items:
     - python
     - python-devel
     - python-pip
     - gcc
     - ansible
  - name: Install shade library for intercating with Openstack clouds
    pip:
     name: openstacksdk       
  - name: Create openstack directory
    file: name=/etc/openstack state=directory
  - name: Create clouds.yaml file
    blockinfile:
     create: yes
     path: /etc/openstack/clouds.yaml
     block: |2
       clouds:
         ospcloud:
           auth:
             auth_url: http://192.168.0.20:5000/
             password: r3dh4t1!
             project_name: admin
             username: admin
           identity_api_version: '3.0'
           region_name: RegionOne
  - name: download RHEL image 
    get_url:
      url: http://www.opentlc.com/download/osp_advanced_networking/rhel-guest-image-7.2-20151102.0.x86_64.qcow2
      dest: /root/rhel-guest-image-7.2-20151102.0.x86_64.qcow2
  - os_image:
      cloud: ospcloud
      name: rhel-guest
      container_format: bare
      disk_format: qcow2
      state: present
      filename: /root/rhel-guest-image-7.2-20151102.0.x86_64.qcow2
